# This is a config for E2B sandbox template.
# You can use template ID (e0xu51xj1gj5b0rvhign) or template name (innovate-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("innovate-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("innovate-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('innovate-nextjs-test-2')

team_id = "8d683339-9170-4c43-b8c2-27d8d04916e3"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "innovate-nextjs-test-2"
template_id = "e0xu51xj1gj5b0rvhign"
